import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type ClinicalDecisionSeed = {
  system: string;
  topic: string;
  clinicalPattern: string;
  decisionType: string;
  prompt: string;
  acceptedAnswers: string[];
  boardPearl: string;
  pivotClue: string;
  commonTrap: string;
  managementPearl: string;
  difficulty: number;
  tags: string[];
};

const decisions: ClinicalDecisionSeed[] = [
  {
    system: "Early Pregnancy",
    topic: "Threatened abortion",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "8 weeks pregnant with vaginal bleeding, closed cervix, and fetal cardiac activity.",
    acceptedAnswers: ["threatened abortion", "threatened miscarriage"],
    boardPearl: "Bleeding with a closed cervix and viable intrauterine pregnancy is threatened abortion.",
    pivotClue: "Closed cervix with fetal cardiac activity",
    commonTrap: "inevitable abortion",
    managementPearl: "Provide reassurance, pelvic rest is not evidence-based, and arrange follow-up.",
    difficulty: 1,
    tags: ["first trimester bleeding", "closed cervix", "viable pregnancy"]
  },
  {
    system: "Early Pregnancy",
    topic: "Inevitable abortion",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "10 weeks pregnant with bleeding, cramping, and an open cervical os.",
    acceptedAnswers: ["inevitable abortion", "inevitable miscarriage"],
    boardPearl: "An open cervix in early pregnancy bleeding means abortion is inevitable or incomplete.",
    pivotClue: "Open cervical os",
    commonTrap: "threatened abortion",
    managementPearl: "Management may be expectant, medical, or surgical depending on stability and preference.",
    difficulty: 1,
    tags: ["first trimester bleeding", "open cervix", "cramping"]
  },
  {
    system: "Early Pregnancy",
    topic: "Incomplete abortion",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "First-trimester bleeding with open os and partial passage of products of conception.",
    acceptedAnswers: ["incomplete abortion", "incomplete miscarriage"],
    boardPearl: "Open os plus partial tissue passage is incomplete abortion.",
    pivotClue: "Partial passage of products of conception",
    commonTrap: "complete abortion",
    managementPearl: "Treat heavy bleeding or infection urgently with uterine evacuation.",
    difficulty: 1,
    tags: ["first trimester bleeding", "products of conception", "open os"]
  },
  {
    system: "Early Pregnancy",
    topic: "Ectopic pregnancy",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "Positive pregnancy test, unilateral pelvic pain, vaginal bleeding, and no intrauterine pregnancy on ultrasound.",
    acceptedAnswers: ["ectopic pregnancy", "tubal ectopic pregnancy"],
    boardPearl: "Pregnancy of unknown location with pain and bleeding is ectopic until proven otherwise.",
    pivotClue: "No intrauterine pregnancy with pain and bleeding",
    commonTrap: "threatened abortion",
    managementPearl: "Assess stability first; unstable patients need urgent surgery.",
    difficulty: 2,
    tags: ["ectopic", "unilateral pain", "first trimester bleeding"]
  },
  {
    system: "Early Pregnancy",
    topic: "Methotrexate for ectopic pregnancy",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Management",
    prompt: "Stable ectopic pregnancy, low beta-hCG, no fetal cardiac activity.",
    acceptedAnswers: ["methotrexate", "medical management with methotrexate"],
    boardPearl: "Stable, unruptured ectopic pregnancy can be treated with methotrexate if criteria are met.",
    pivotClue: "Stable unruptured ectopic pregnancy",
    commonTrap: "laparotomy",
    managementPearl: "Use methotrexate only when stable and reliable follow-up is possible.",
    difficulty: 2,
    tags: ["ectopic", "methotrexate", "stable"]
  },
  {
    system: "Early Pregnancy",
    topic: "Molar pregnancy",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "First-trimester bleeding, uterus larger than dates, very high beta-hCG, and hyperemesis.",
    acceptedAnswers: ["molar pregnancy", "hydatidiform mole", "gestational trophoblastic disease"],
    boardPearl: "Very high beta-hCG with a large uterus and bleeding suggests molar pregnancy.",
    pivotClue: "Very high beta-hCG and uterus larger than dates",
    commonTrap: "hyperemesis gravidarum",
    managementPearl: "Treat with suction curettage and follow serial beta-hCG.",
    difficulty: 2,
    tags: ["molar pregnancy", "high beta hcg", "first trimester bleeding"]
  },
  {
    system: "Early Pregnancy",
    topic: "Rh immune globulin",
    clinicalPattern: "First-trimester bleeding",
    decisionType: "Next Best Step",
    prompt: "Rh-negative patient with first-trimester bleeding.",
    acceptedAnswers: ["rh immune globulin", "rho(d) immune globulin", "rhogam"],
    boardPearl: "Give Rh immune globulin to unsensitized Rh-negative patients with pregnancy bleeding.",
    pivotClue: "Rh-negative pregnancy bleeding",
    commonTrap: "observation only",
    managementPearl: "Administer Rh immune globulin to prevent alloimmunization.",
    difficulty: 1,
    tags: ["rh negative", "bleeding", "rhogam"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Placenta previa",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "32 weeks pregnant with painless bright red vaginal bleeding.",
    acceptedAnswers: ["placenta previa", "previa"],
    boardPearl: "Painless third-trimester bleeding is placenta previa until proven otherwise.",
    pivotClue: "Painless bright red bleeding",
    commonTrap: "placental abruption",
    managementPearl: "Avoid digital cervical exam until previa is excluded.",
    difficulty: 1,
    tags: ["third trimester bleeding", "painless bleeding", "previa"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Placenta previa evaluation",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Initial Test",
    prompt: "Third-trimester bleeding with suspected placenta previa.",
    acceptedAnswers: ["transvaginal ultrasound", "ultrasound", "pelvic ultrasound"],
    boardPearl: "Transvaginal ultrasound is safe and best for diagnosing placenta previa.",
    pivotClue: "Suspected placenta previa",
    commonTrap: "digital cervical examination",
    managementPearl: "Localize the placenta before any cervical exam.",
    difficulty: 1,
    tags: ["previa", "ultrasound", "third trimester bleeding"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Digital exam in placenta previa",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Contraindication",
    prompt: "Suspected placenta previa.",
    acceptedAnswers: ["digital cervical examination", "digital cervical exam", "cervical exam"],
    boardPearl: "Digital cervical exam is contraindicated until placenta previa is excluded.",
    pivotClue: "Suspected placenta previa",
    commonTrap: "check cervical dilation",
    managementPearl: "Use ultrasound first to prevent provoking severe hemorrhage.",
    difficulty: 1,
    tags: ["previa", "contraindication", "digital exam"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Placental abruption",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "Third-trimester bleeding with painful contractions and a tender rigid uterus.",
    acceptedAnswers: ["placental abruption", "abruptio placentae", "abruption"],
    boardPearl: "Painful bleeding with uterine tenderness suggests placental abruption.",
    pivotClue: "Tender rigid uterus with painful bleeding",
    commonTrap: "placenta previa",
    managementPearl: "Stabilize mother first and deliver if maternal or fetal instability is present.",
    difficulty: 1,
    tags: ["abruption", "third trimester bleeding", "uterine tenderness"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Vasa previa",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "Rupture of membranes followed by painless bleeding and fetal bradycardia.",
    acceptedAnswers: ["vasa previa"],
    boardPearl: "Bleeding after membrane rupture with fetal bradycardia is vasa previa.",
    pivotClue: "Bleeding after rupture of membranes with fetal bradycardia",
    commonTrap: "placenta previa",
    managementPearl: "Perform emergent cesarean delivery.",
    difficulty: 2,
    tags: ["vasa previa", "fetal bradycardia", "rom"]
  },
  {
    system: "Antepartum Bleeding",
    topic: "Uterine rupture",
    clinicalPattern: "Third-trimester bleeding",
    decisionType: "Diagnosis",
    prompt: "TOLAC patient with sudden abdominal pain, vaginal bleeding, and loss of fetal station.",
    acceptedAnswers: ["uterine rupture"],
    boardPearl: "Loss of fetal station after prior uterine surgery is classic for uterine rupture.",
    pivotClue: "Loss of fetal station during TOLAC",
    commonTrap: "placental abruption",
    managementPearl: "Proceed to emergent laparotomy and delivery.",
    difficulty: 2,
    tags: ["tolac", "uterine rupture", "loss of station"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Gestational hypertension",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Diagnosis",
    prompt: "New hypertension after 20 weeks with no proteinuria or end-organ symptoms.",
    acceptedAnswers: ["gestational hypertension"],
    boardPearl: "Hypertension after 20 weeks without proteinuria or severe features is gestational hypertension.",
    pivotClue: "No proteinuria or end-organ symptoms",
    commonTrap: "preeclampsia",
    managementPearl: "Monitor closely because gestational hypertension can progress to preeclampsia.",
    difficulty: 1,
    tags: ["gestational hypertension", "20 weeks", "hypertension"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Preeclampsia without severe features",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Diagnosis",
    prompt: "Hypertension after 20 weeks with proteinuria and no severe features.",
    acceptedAnswers: ["preeclampsia without severe features", "mild preeclampsia", "preeclampsia"],
    boardPearl: "Hypertension after 20 weeks plus proteinuria is preeclampsia.",
    pivotClue: "Proteinuria after 20 weeks",
    commonTrap: "gestational hypertension",
    managementPearl: "Deliver at 37 weeks if no severe features.",
    difficulty: 1,
    tags: ["preeclampsia", "proteinuria", "hypertension"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Preeclampsia with severe features",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Diagnosis",
    prompt: "34 weeks with BP 168/112, headache, RUQ pain, platelets 88,000.",
    acceptedAnswers: ["preeclampsia with severe features", "severe preeclampsia"],
    boardPearl: "Severe-range BP or end-organ injury makes preeclampsia severe.",
    pivotClue: "Severe BP plus end-organ symptoms",
    commonTrap: "gestational hypertension",
    managementPearl: "Give magnesium sulfate and plan delivery.",
    difficulty: 1,
    tags: ["severe preeclampsia", "platelets", "ruq pain"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Magnesium sulfate",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Management",
    prompt: "Preeclampsia with severe features.",
    acceptedAnswers: ["magnesium sulfate", "magnesium"],
    boardPearl: "Magnesium sulfate prevents seizures in severe preeclampsia and treats eclampsia.",
    pivotClue: "Severe features",
    commonTrap: "labetalol only",
    managementPearl: "Use magnesium for seizure prophylaxis; antihypertensives treat severe BP.",
    difficulty: 1,
    tags: ["magnesium", "preeclampsia", "seizure prophylaxis"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Eclampsia",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Diagnosis",
    prompt: "Pregnant patient with preeclampsia develops a generalized seizure.",
    acceptedAnswers: ["eclampsia"],
    boardPearl: "Seizure in a patient with preeclampsia is eclampsia.",
    pivotClue: "Generalized seizure",
    commonTrap: "epilepsy",
    managementPearl: "Give magnesium sulfate, stabilize, then deliver.",
    difficulty: 1,
    tags: ["eclampsia", "seizure", "preeclampsia"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "HELLP syndrome",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Diagnosis",
    prompt: "Pregnant patient with RUQ pain, hemolysis, elevated LFTs, and low platelets.",
    acceptedAnswers: ["hellp syndrome", "hellp"],
    boardPearl: "HELLP is hemolysis, elevated liver enzymes, and low platelets.",
    pivotClue: "Hemolysis plus elevated LFTs plus low platelets",
    commonTrap: "acute fatty liver of pregnancy",
    managementPearl: "Stabilize and deliver regardless of gestational age if severe.",
    difficulty: 2,
    tags: ["hellp", "ruq pain", "low platelets"]
  },
  {
    system: "Hypertension in Pregnancy",
    topic: "Severe hypertension treatment",
    clinicalPattern: "Hypertension in pregnancy",
    decisionType: "Management",
    prompt: "Pregnancy with persistent BP 170/115.",
    acceptedAnswers: ["iv labetalol", "labetalol", "hydralazine", "nifedipine"],
    boardPearl: "Acute severe hypertension in pregnancy requires prompt antihypertensive therapy.",
    pivotClue: "Persistent severe-range blood pressure",
    commonTrap: "observe only",
    managementPearl: "Use IV labetalol, IV hydralazine, or oral nifedipine.",
    difficulty: 2,
    tags: ["severe hypertension", "labetalol", "hydralazine"]
  },
  {
    system: "Labor and Delivery",
    topic: "Active labor",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Diagnosis",
    prompt: "Regular contractions with cervical dilation from 6 to 8 cm.",
    acceptedAnswers: ["active labor", "active phase of labor"],
    boardPearl: "Active labor begins at about 6 cm cervical dilation.",
    pivotClue: "Cervical dilation at or beyond 6 cm",
    commonTrap: "latent labor",
    managementPearl: "Track cervical change and fetal status.",
    difficulty: 1,
    tags: ["labor", "active phase", "cervical dilation"]
  },
  {
    system: "Labor and Delivery",
    topic: "Category I fetal tracing",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Diagnosis",
    prompt: "Baseline 140, moderate variability, accelerations, no decelerations.",
    acceptedAnswers: ["category i tracing", "category 1 tracing", "normal fetal heart tracing"],
    boardPearl: "Moderate variability without concerning decelerations is reassuring.",
    pivotClue: "Moderate variability",
    commonTrap: "category ii tracing",
    managementPearl: "Continue routine monitoring.",
    difficulty: 1,
    tags: ["fetal monitoring", "category i", "moderate variability"]
  },
  {
    system: "Labor and Delivery",
    topic: "Late decelerations",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Diagnosis",
    prompt: "Fetal heart rate decelerations begin after contractions and recover after contractions end.",
    acceptedAnswers: ["late decelerations", "uteroplacental insufficiency"],
    boardPearl: "Late decelerations reflect uteroplacental insufficiency.",
    pivotClue: "Deceleration starts after contraction begins",
    commonTrap: "early decelerations",
    managementPearl: "Reposition, give fluids, stop oxytocin, and correct hypotension.",
    difficulty: 1,
    tags: ["late decelerations", "uteroplacental insufficiency", "fetal monitoring"]
  },
  {
    system: "Labor and Delivery",
    topic: "Variable decelerations",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Diagnosis",
    prompt: "Abrupt fetal heart rate drops with rapid return to baseline during labor.",
    acceptedAnswers: ["variable decelerations", "cord compression", "umbilical cord compression"],
    boardPearl: "Variable decelerations are caused by umbilical cord compression.",
    pivotClue: "Abrupt drop and rapid recovery",
    commonTrap: "late decelerations",
    managementPearl: "Reposition; consider amnioinfusion for recurrent variables.",
    difficulty: 1,
    tags: ["variable decelerations", "cord compression", "fetal monitoring"]
  },
  {
    system: "Labor and Delivery",
    topic: "Shoulder dystocia",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Management",
    prompt: "Turtle sign after delivery of fetal head.",
    acceptedAnswers: ["mcroberts maneuver", "mcroberts", "suprapubic pressure"],
    boardPearl: "McRoberts maneuver is first-line for shoulder dystocia.",
    pivotClue: "Turtle sign",
    commonTrap: "fundal pressure",
    managementPearl: "Use McRoberts and suprapubic pressure; avoid fundal pressure.",
    difficulty: 1,
    tags: ["shoulder dystocia", "mcroberts", "turtle sign"]
  },
  {
    system: "Labor and Delivery",
    topic: "Cord prolapse",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Management",
    prompt: "Sudden fetal bradycardia after rupture of membranes with palpable cord.",
    acceptedAnswers: ["emergency cesarean delivery", "emergent cesarean", "cesarean delivery"],
    boardPearl: "Cord prolapse causes sudden fetal bradycardia after membrane rupture.",
    pivotClue: "Palpable cord after rupture of membranes",
    commonTrap: "amnioinfusion",
    managementPearl: "Elevate presenting part and proceed to emergency cesarean.",
    difficulty: 2,
    tags: ["cord prolapse", "fetal bradycardia", "rom"]
  },
  {
    system: "Labor and Delivery",
    topic: "Tachysystole",
    clinicalPattern: "Labor and fetal monitoring",
    decisionType: "Management",
    prompt: "Oxytocin induction with more than 5 contractions in 10 minutes.",
    acceptedAnswers: ["stop oxytocin", "discontinue oxytocin", "stop pitocin"],
    boardPearl: "Tachysystole is more than 5 contractions in 10 minutes.",
    pivotClue: "More than 5 contractions in 10 minutes",
    commonTrap: "increase oxytocin",
    managementPearl: "Stop oxytocin and resuscitate intrauterine environment.",
    difficulty: 1,
    tags: ["tachysystole", "oxytocin", "pitocin"]
  },
  {
    system: "Postpartum",
    topic: "Uterine atony",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Diagnosis",
    prompt: "Postpartum hemorrhage with boggy enlarged uterus.",
    acceptedAnswers: ["uterine atony", "atony"],
    boardPearl: "Uterine atony is the most common cause of postpartum hemorrhage.",
    pivotClue: "Boggy enlarged uterus",
    commonTrap: "retained placenta",
    managementPearl: "Start uterine massage and oxytocin.",
    difficulty: 1,
    tags: ["postpartum hemorrhage", "boggy uterus", "uterine atony"]
  },
  {
    system: "Postpartum",
    topic: "Initial postpartum hemorrhage management",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Next Best Step",
    prompt: "Heavy postpartum bleeding with boggy uterus.",
    acceptedAnswers: ["uterine massage and oxytocin", "fundal massage and oxytocin", "oxytocin"],
    boardPearl: "Uterine massage and oxytocin are first-line for uterine atony.",
    pivotClue: "Boggy uterus",
    commonTrap: "methylergonovine first",
    managementPearl: "Massage the uterus and give oxytocin before second-line uterotonics.",
    difficulty: 1,
    tags: ["postpartum hemorrhage", "oxytocin", "uterine massage"]
  },
  {
    system: "Postpartum",
    topic: "Methylergonovine contraindication",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Contraindication",
    prompt: "Postpartum hemorrhage in a patient with severe hypertension.",
    acceptedAnswers: ["methylergonovine", "methergine"],
    boardPearl: "Methylergonovine is contraindicated in hypertension.",
    pivotClue: "Severe hypertension",
    commonTrap: "carboprost",
    managementPearl: "Avoid methylergonovine; choose another uterotonic.",
    difficulty: 1,
    tags: ["postpartum hemorrhage", "methylergonovine", "hypertension"]
  },
  {
    system: "Postpartum",
    topic: "Carboprost contraindication",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Contraindication",
    prompt: "Postpartum hemorrhage in a patient with asthma.",
    acceptedAnswers: ["carboprost", "hemabate", "prostaglandin f2 alpha"],
    boardPearl: "Carboprost is contraindicated in asthma.",
    pivotClue: "Asthma",
    commonTrap: "methylergonovine",
    managementPearl: "Avoid carboprost because it can cause bronchospasm.",
    difficulty: 1,
    tags: ["postpartum hemorrhage", "carboprost", "asthma"]
  },
  {
    system: "Postpartum",
    topic: "Retained placenta",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Diagnosis",
    prompt: "Postpartum hemorrhage with placenta not delivered after 30 minutes.",
    acceptedAnswers: ["retained placenta"],
    boardPearl: "Failure to deliver the placenta within 30 minutes suggests retained placenta.",
    pivotClue: "Placenta undelivered after 30 minutes",
    commonTrap: "uterine atony",
    managementPearl: "Manual extraction is indicated when placenta is retained.",
    difficulty: 1,
    tags: ["postpartum hemorrhage", "retained placenta", "30 minutes"]
  },
  {
    system: "Postpartum",
    topic: "Uterine inversion",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Diagnosis",
    prompt: "Postpartum hemorrhage, shock, and a fundal mass protruding through the cervix.",
    acceptedAnswers: ["uterine inversion"],
    boardPearl: "Uterine inversion causes hemorrhage and shock after delivery.",
    pivotClue: "Fundal mass protruding through cervix",
    commonTrap: "uterine prolapse",
    managementPearl: "Immediately replace the uterus before giving uterotonics.",
    difficulty: 2,
    tags: ["postpartum hemorrhage", "uterine inversion", "shock"]
  },
  {
    system: "Postpartum",
    topic: "Amniotic fluid embolism",
    clinicalPattern: "Postpartum hemorrhage",
    decisionType: "Diagnosis",
    prompt: "Sudden hypoxia, hypotension, DIC during labor or immediately postpartum.",
    acceptedAnswers: ["amniotic fluid embolism"],
    boardPearl: "Amniotic fluid embolism presents with sudden hypoxia, shock, and DIC.",
    pivotClue: "Hypoxia plus hypotension plus DIC",
    commonTrap: "pulmonary embolism",
    managementPearl: "Provide supportive critical care and correct coagulopathy.",
    difficulty: 2,
    tags: ["amniotic fluid embolism", "dic", "hypoxia"]
  },
  {
    system: "Postpartum",
    topic: "Endometritis",
    clinicalPattern: "Postpartum fever",
    decisionType: "Diagnosis",
    prompt: "Postpartum fever with uterine tenderness and foul-smelling lochia.",
    acceptedAnswers: ["endometritis", "postpartum endometritis"],
    boardPearl: "Postpartum fever with uterine tenderness is endometritis.",
    pivotClue: "Uterine tenderness and foul lochia",
    commonTrap: "mastitis",
    managementPearl: "Treat with broad-spectrum IV clindamycin plus gentamicin.",
    difficulty: 1,
    tags: ["postpartum fever", "endometritis", "foul lochia"]
  },
  {
    system: "Postpartum",
    topic: "Endometritis treatment",
    clinicalPattern: "Postpartum fever",
    decisionType: "Management",
    prompt: "Postpartum endometritis.",
    acceptedAnswers: ["clindamycin and gentamicin", "iv clindamycin plus gentamicin"],
    boardPearl: "Clindamycin plus gentamicin is classic treatment for postpartum endometritis.",
    pivotClue: "Postpartum uterine infection",
    commonTrap: "oral cephalexin",
    managementPearl: "Use broad-spectrum IV antibiotics until afebrile.",
    difficulty: 1,
    tags: ["endometritis", "clindamycin", "gentamicin"]
  },
  {
    system: "Postpartum",
    topic: "Mastitis",
    clinicalPattern: "Postpartum fever",
    decisionType: "Diagnosis",
    prompt: "Breastfeeding patient with fever and a painful erythematous wedge-shaped breast area.",
    acceptedAnswers: ["mastitis", "lactational mastitis"],
    boardPearl: "Mastitis is fever with focal breast erythema and pain during lactation.",
    pivotClue: "Wedge-shaped painful erythema in breastfeeding",
    commonTrap: "breast engorgement",
    managementPearl: "Continue breastfeeding and treat with anti-staphylococcal antibiotics.",
    difficulty: 1,
    tags: ["postpartum fever", "mastitis", "breastfeeding"]
  },
  {
    system: "Postpartum",
    topic: "Breast abscess",
    clinicalPattern: "Postpartum fever",
    decisionType: "Diagnosis",
    prompt: "Mastitis symptoms with persistent fever and fluctuant breast mass.",
    acceptedAnswers: ["breast abscess"],
    boardPearl: "A fluctuant mass after mastitis suggests breast abscess.",
    pivotClue: "Fluctuant breast mass",
    commonTrap: "uncomplicated mastitis",
    managementPearl: "Drain the abscess and give antibiotics.",
    difficulty: 1,
    tags: ["postpartum fever", "breast abscess", "fluctuant"]
  },
  {
    system: "Postpartum",
    topic: "Septic pelvic thrombophlebitis",
    clinicalPattern: "Postpartum fever",
    decisionType: "Diagnosis",
    prompt: "Persistent postpartum fever despite broad-spectrum antibiotics and negative workup.",
    acceptedAnswers: ["septic pelvic thrombophlebitis"],
    boardPearl: "Persistent postpartum fever despite antibiotics suggests septic pelvic thrombophlebitis.",
    pivotClue: "Fever persists despite antibiotics",
    commonTrap: "endometritis",
    managementPearl: "Treat with anticoagulation plus antibiotics.",
    difficulty: 2,
    tags: ["postpartum fever", "septic pelvic thrombophlebitis", "persistent fever"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Bacterial vaginosis",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Diagnosis",
    prompt: "Thin gray discharge with fishy odor and clue cells.",
    acceptedAnswers: ["bacterial vaginosis", "bv"],
    boardPearl: "Clue cells and fishy odor point to bacterial vaginosis.",
    pivotClue: "Clue cells",
    commonTrap: "trichomoniasis",
    managementPearl: "Treat symptomatic BV with metronidazole.",
    difficulty: 1,
    tags: ["vaginal discharge", "clue cells", "fishy odor"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Trichomoniasis",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Diagnosis",
    prompt: "Frothy green discharge, strawberry cervix, and motile organisms.",
    acceptedAnswers: ["trichomoniasis", "trichomonas"],
    boardPearl: "Motile trichomonads with frothy discharge indicate trichomoniasis.",
    pivotClue: "Motile organisms and strawberry cervix",
    commonTrap: "bacterial vaginosis",
    managementPearl: "Treat patient and partners with metronidazole.",
    difficulty: 1,
    tags: ["trichomonas", "frothy discharge", "strawberry cervix"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Vulvovaginal candidiasis",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Diagnosis",
    prompt: "Thick white discharge with vulvar pruritus and pseudohyphae.",
    acceptedAnswers: ["vulvovaginal candidiasis", "candida vaginitis", "yeast infection"],
    boardPearl: "Pruritus with thick white discharge and pseudohyphae is candidiasis.",
    pivotClue: "Pseudohyphae",
    commonTrap: "bacterial vaginosis",
    managementPearl: "Treat with topical azole or oral fluconazole if not pregnant.",
    difficulty: 1,
    tags: ["candida", "pseudohyphae", "pruritus"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Cervicitis",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Diagnosis",
    prompt: "Mucopurulent cervical discharge and friable cervix.",
    acceptedAnswers: ["cervicitis", "chlamydial cervicitis", "gonococcal cervicitis"],
    boardPearl: "Mucopurulent discharge and friability suggest cervicitis.",
    pivotClue: "Friable cervix",
    commonTrap: "vaginitis",
    managementPearl: "Test for gonorrhea and chlamydia and treat empirically when indicated.",
    difficulty: 1,
    tags: ["cervicitis", "mucopurulent", "friable cervix"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Pelvic inflammatory disease",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Diagnosis",
    prompt: "Pelvic pain, fever, cervical motion tenderness, and mucopurulent discharge.",
    acceptedAnswers: ["pelvic inflammatory disease", "pid"],
    boardPearl: "Cervical motion tenderness with pelvic pain suggests PID.",
    pivotClue: "Cervical motion tenderness",
    commonTrap: "cervicitis only",
    managementPearl: "Treat empirically to prevent infertility and chronic pelvic pain.",
    difficulty: 1,
    tags: ["pid", "cervical motion tenderness", "sti"]
  },
  {
    system: "Infectious Gynecology",
    topic: "PID complication",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Complication",
    prompt: "History of untreated PID.",
    acceptedAnswers: ["infertility", "ectopic pregnancy", "chronic pelvic pain"],
    boardPearl: "PID can scar fallopian tubes and cause infertility or ectopic pregnancy.",
    pivotClue: "Untreated PID",
    commonTrap: "ovarian cancer",
    managementPearl: "Early empiric treatment reduces long-term sequelae.",
    difficulty: 1,
    tags: ["pid", "infertility", "ectopic"]
  },
  {
    system: "Infectious Gynecology",
    topic: "Chlamydia treatment in pregnancy",
    clinicalPattern: "Vaginal discharge / STIs",
    decisionType: "Management",
    prompt: "Pregnant patient with positive chlamydia NAAT.",
    acceptedAnswers: ["azithromycin", "azithromycin treatment"],
    boardPearl: "Azithromycin is preferred for chlamydia in pregnancy.",
    pivotClue: "Pregnancy with chlamydia",
    commonTrap: "doxycycline",
    managementPearl: "Avoid doxycycline in pregnancy.",
    difficulty: 1,
    tags: ["chlamydia", "pregnancy", "azithromycin"]
  },
  {
    system: "Gynecologic Pain",
    topic: "Ovarian torsion",
    clinicalPattern: "Acute pelvic pain",
    decisionType: "Diagnosis",
    prompt: "Sudden unilateral pelvic pain with nausea and enlarged ovary.",
    acceptedAnswers: ["ovarian torsion", "adnexal torsion"],
    boardPearl: "Sudden unilateral pelvic pain with nausea suggests ovarian torsion.",
    pivotClue: "Sudden unilateral pain with nausea",
    commonTrap: "ruptured ovarian cyst",
    managementPearl: "Urgent diagnostic laparoscopy is indicated when torsion is suspected.",
    difficulty: 1,
    tags: ["ovarian torsion", "acute pelvic pain", "nausea"]
  },
  {
    system: "Gynecologic Pain",
    topic: "Ovarian torsion management",
    clinicalPattern: "Acute pelvic pain",
    decisionType: "Next Best Step",
    prompt: "High suspicion for ovarian torsion.",
    acceptedAnswers: ["diagnostic laparoscopy", "urgent laparoscopy", "surgical detorsion"],
    boardPearl: "Do not delay surgery for imaging when torsion suspicion is high.",
    pivotClue: "High suspicion for torsion",
    commonTrap: "observe with analgesics",
    managementPearl: "Urgent laparoscopy preserves ovarian function.",
    difficulty: 2,
    tags: ["ovarian torsion", "laparoscopy", "detorsion"]
  },
  {
    system: "Gynecologic Pain",
    topic: "Ruptured ovarian cyst",
    clinicalPattern: "Acute pelvic pain",
    decisionType: "Diagnosis",
    prompt: "Sudden unilateral pelvic pain after intercourse with free pelvic fluid.",
    acceptedAnswers: ["ruptured ovarian cyst", "ruptured cyst"],
    boardPearl: "Ruptured ovarian cyst often causes sudden pain with free fluid.",
    pivotClue: "Free pelvic fluid after sudden pain",
    commonTrap: "ovarian torsion",
    managementPearl: "Stable patients can usually be managed supportively.",
    difficulty: 1,
    tags: ["ruptured cyst", "acute pelvic pain", "free fluid"]
  },
  {
    system: "Gynecologic Pain",
    topic: "Endometriosis",
    clinicalPattern: "Acute pelvic pain",
    decisionType: "Diagnosis",
    prompt: "Chronic cyclic pelvic pain, dysmenorrhea, dyspareunia, and infertility.",
    acceptedAnswers: ["endometriosis"],
    boardPearl: "Cyclic pelvic pain with dyspareunia and infertility suggests endometriosis.",
    pivotClue: "Cyclic pain with infertility",
    commonTrap: "pelvic inflammatory disease",
    managementPearl: "Empiric NSAIDs and hormonal suppression are first-line if uncomplicated.",
    difficulty: 1,
    tags: ["endometriosis", "dysmenorrhea", "dyspareunia"]
  },
  {
    system: "Gynecologic Pain",
    topic: "Degenerating fibroid",
    clinicalPattern: "Acute pelvic pain",
    decisionType: "Diagnosis",
    prompt: "Pregnant patient with localized uterine pain and known fibroids.",
    acceptedAnswers: ["red degeneration of fibroid", "degenerating fibroid", "fibroid degeneration"],
    boardPearl: "Fibroids can undergo painful red degeneration during pregnancy.",
    pivotClue: "Pregnancy with known fibroids and focal uterine pain",
    commonTrap: "placental abruption",
    managementPearl: "Treat supportively with analgesia if maternal-fetal status is reassuring.",
    difficulty: 2,
    tags: ["fibroid", "pregnancy", "red degeneration"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Pregnancy test",
    clinicalPattern: "Amenorrhea",
    decisionType: "Initial Test",
    prompt: "Reproductive-age patient with secondary amenorrhea.",
    acceptedAnswers: ["pregnancy test", "urine pregnancy test", "beta-hcg", "serum beta-hcg"],
    boardPearl: "Pregnancy test is always first in secondary amenorrhea.",
    pivotClue: "Reproductive-age amenorrhea",
    commonTrap: "tsh first",
    managementPearl: "Rule out pregnancy before endocrine workup.",
    difficulty: 1,
    tags: ["amenorrhea", "pregnancy test", "beta hcg"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Functional hypothalamic amenorrhea",
    clinicalPattern: "Amenorrhea",
    decisionType: "Diagnosis",
    prompt: "Amenorrhea after weight loss, intense exercise, and stress.",
    acceptedAnswers: ["functional hypothalamic amenorrhea", "hypothalamic amenorrhea"],
    boardPearl: "Stress, weight loss, and exercise suppress GnRH pulsatility.",
    pivotClue: "Weight loss and intense exercise",
    commonTrap: "pcos",
    managementPearl: "Restore energy balance and address stressors.",
    difficulty: 1,
    tags: ["amenorrhea", "weight loss", "exercise"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "PCOS",
    clinicalPattern: "Amenorrhea",
    decisionType: "Diagnosis",
    prompt: "Irregular menses, hirsutism, acne, and polycystic ovaries.",
    acceptedAnswers: ["polycystic ovary syndrome", "pcos"],
    boardPearl: "PCOS causes chronic anovulation plus hyperandrogenism.",
    pivotClue: "Hyperandrogenism with irregular menses",
    commonTrap: "hypothalamic amenorrhea",
    managementPearl: "Treat menstrual irregularity with combined OCPs if not trying to conceive.",
    difficulty: 1,
    tags: ["pcos", "hirsutism", "anovulation"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Primary ovarian insufficiency",
    clinicalPattern: "Amenorrhea",
    decisionType: "Diagnosis",
    prompt: "Amenorrhea before age 40 with hot flashes and elevated FSH.",
    acceptedAnswers: ["primary ovarian insufficiency", "premature ovarian insufficiency"],
    boardPearl: "High FSH with amenorrhea before 40 suggests primary ovarian insufficiency.",
    pivotClue: "Elevated FSH before age 40",
    commonTrap: "menopause",
    managementPearl: "Give hormone therapy unless contraindicated to protect bone and cardiovascular health.",
    difficulty: 2,
    tags: ["amenorrhea", "high fsh", "primary ovarian insufficiency"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Asherman syndrome",
    clinicalPattern: "Amenorrhea",
    decisionType: "Diagnosis",
    prompt: "Secondary amenorrhea after dilation and curettage.",
    acceptedAnswers: ["asherman syndrome", "intrauterine adhesions"],
    boardPearl: "Amenorrhea after uterine instrumentation suggests Asherman syndrome.",
    pivotClue: "History of D&C",
    commonTrap: "hypothalamic amenorrhea",
    managementPearl: "Diagnose and treat with hysteroscopy.",
    difficulty: 2,
    tags: ["asherman", "amenorrhea", "d and c"]
  },
  {
    system: "Benign Gynecology",
    topic: "Anovulatory bleeding",
    clinicalPattern: "Abnormal uterine bleeding",
    decisionType: "Diagnosis",
    prompt: "Adolescent with irregular heavy bleeding since menarche.",
    acceptedAnswers: ["anovulatory bleeding", "anovulatory abnormal uterine bleeding"],
    boardPearl: "Immature HPO axis commonly causes anovulatory bleeding in adolescents.",
    pivotClue: "Irregular bleeding since menarche",
    commonTrap: "fibroids",
    managementPearl: "Exclude pregnancy and bleeding disorders when clinically indicated.",
    difficulty: 1,
    tags: ["aub", "anovulatory", "adolescent"]
  },
  {
    system: "Benign Gynecology",
    topic: "Endometrial biopsy indication",
    clinicalPattern: "Abnormal uterine bleeding",
    decisionType: "Next Best Step",
    prompt: "Abnormal uterine bleeding in a 48-year-old.",
    acceptedAnswers: ["endometrial biopsy", "endometrial sampling"],
    boardPearl: "AUB at age 45 or older requires endometrial sampling.",
    pivotClue: "Age 45 or older",
    commonTrap: "trial of OCPs only",
    managementPearl: "Sample the endometrium to exclude hyperplasia or malignancy.",
    difficulty: 1,
    tags: ["aub", "endometrial biopsy", "age 45"]
  },
  {
    system: "Benign Gynecology",
    topic: "Leiomyomas",
    clinicalPattern: "Abnormal uterine bleeding",
    decisionType: "Diagnosis",
    prompt: "Heavy regular menses with enlarged irregular mobile uterus.",
    acceptedAnswers: ["leiomyomas", "uterine fibroids", "fibroids"],
    boardPearl: "Heavy regular bleeding with enlarged irregular uterus suggests fibroids.",
    pivotClue: "Enlarged irregular mobile uterus",
    commonTrap: "adenomyosis",
    managementPearl: "Ultrasound confirms; treatment depends on symptoms and fertility goals.",
    difficulty: 1,
    tags: ["fibroids", "aub", "leiomyoma"]
  },
  {
    system: "Benign Gynecology",
    topic: "Adenomyosis",
    clinicalPattern: "Abnormal uterine bleeding",
    decisionType: "Diagnosis",
    prompt: "Heavy painful menses with uniformly enlarged boggy uterus.",
    acceptedAnswers: ["adenomyosis"],
    boardPearl: "Adenomyosis causes dysmenorrhea with a diffusely enlarged boggy uterus.",
    pivotClue: "Uniformly enlarged boggy uterus",
    commonTrap: "leiomyomas",
    managementPearl: "Hysterectomy is definitive if childbearing is complete.",
    difficulty: 1,
    tags: ["adenomyosis", "aub", "boggy uterus"]
  },
  {
    system: "Benign Gynecology",
    topic: "Endometrial polyp",
    clinicalPattern: "Abnormal uterine bleeding",
    decisionType: "Diagnosis",
    prompt: "Intermenstrual spotting with focal endometrial lesion on saline sonogram.",
    acceptedAnswers: ["endometrial polyp", "uterine polyp"],
    boardPearl: "Endometrial polyps commonly cause intermenstrual bleeding.",
    pivotClue: "Focal endometrial lesion",
    commonTrap: "anovulatory bleeding",
    managementPearl: "Hysteroscopic polypectomy is diagnostic and therapeutic.",
    difficulty: 2,
    tags: ["endometrial polyp", "intermenstrual bleeding", "aub"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Infertility evaluation timing",
    clinicalPattern: "Infertility",
    decisionType: "Board Pearl",
    prompt: "Trying to conceive for 12 months without pregnancy.",
    acceptedAnswers: ["start infertility evaluation", "infertility evaluation", "evaluate infertility"],
    boardPearl: "Infertility is failure to conceive after 12 months, or 6 months if age 35 or older.",
    pivotClue: "12 months trying to conceive",
    commonTrap: "reassure indefinitely",
    managementPearl: "Begin evaluation of both partners.",
    difficulty: 1,
    tags: ["infertility", "12 months", "evaluation"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Male factor infertility",
    clinicalPattern: "Infertility",
    decisionType: "Initial Test",
    prompt: "Couple with infertility beginning evaluation.",
    acceptedAnswers: ["semen analysis", "semen analysis of male partner"],
    boardPearl: "Semen analysis is an early, low-cost infertility test.",
    pivotClue: "Couple infertility evaluation",
    commonTrap: "diagnostic laparoscopy first",
    managementPearl: "Evaluate male and female factors in parallel.",
    difficulty: 1,
    tags: ["infertility", "semen analysis", "male factor"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Ovulatory dysfunction",
    clinicalPattern: "Infertility",
    decisionType: "Initial Test",
    prompt: "Infertility with irregular menses.",
    acceptedAnswers: ["midluteal progesterone", "serum progesterone", "ovulation assessment"],
    boardPearl: "Midluteal progesterone can confirm ovulation.",
    pivotClue: "Irregular menses",
    commonTrap: "hysterosalpingogram first",
    managementPearl: "Assess ovulation when cycles are irregular.",
    difficulty: 2,
    tags: ["infertility", "anovulation", "progesterone"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Tubal factor infertility",
    clinicalPattern: "Infertility",
    decisionType: "Initial Test",
    prompt: "Infertility with history of PID.",
    acceptedAnswers: ["hysterosalpingography", "hysterosalpingogram", "hsg"],
    boardPearl: "Hysterosalpingography evaluates tubal patency.",
    pivotClue: "History of PID",
    commonTrap: "semen analysis only",
    managementPearl: "Use HSG to assess for tubal scarring.",
    difficulty: 1,
    tags: ["infertility", "pid", "hsg"]
  },
  {
    system: "Reproductive Endocrinology",
    topic: "Clomiphene or letrozole",
    clinicalPattern: "Infertility",
    decisionType: "Management",
    prompt: "PCOS patient trying to conceive.",
    acceptedAnswers: ["letrozole", "clomiphene", "ovulation induction"],
    boardPearl: "Ovulation induction is used for anovulatory infertility in PCOS.",
    pivotClue: "PCOS trying to conceive",
    commonTrap: "combined oral contraceptives",
    managementPearl: "Use letrozole or clomiphene for ovulation induction.",
    difficulty: 2,
    tags: ["infertility", "pcos", "ovulation induction"]
  },
  {
    system: "Breast",
    topic: "Fibroadenoma",
    clinicalPattern: "Breast mass / breast disease",
    decisionType: "Diagnosis",
    prompt: "Young woman with firm rubbery mobile breast mass.",
    acceptedAnswers: ["fibroadenoma"],
    boardPearl: "Fibroadenoma is a firm, mobile, rubbery mass in young women.",
    pivotClue: "Firm rubbery mobile mass",
    commonTrap: "breast cancer",
    managementPearl: "Ultrasound is typically used first in young patients.",
    difficulty: 1,
    tags: ["breast mass", "fibroadenoma", "mobile"]
  },
  {
    system: "Breast",
    topic: "Breast cyst",
    clinicalPattern: "Breast mass / breast disease",
    decisionType: "Diagnosis",
    prompt: "Premenopausal patient with smooth tender breast mass that varies with cycle.",
    acceptedAnswers: ["breast cyst", "fibrocystic change", "fibrocystic changes"],
    boardPearl: "Cyclic tender breast masses suggest cystic or fibrocystic disease.",
    pivotClue: "Cyclic tenderness",
    commonTrap: "fibroadenoma",
    managementPearl: "Ultrasound distinguishes cystic from solid masses.",
    difficulty: 1,
    tags: ["breast mass", "cyst", "cyclic pain"]
  },
  {
    system: "Breast",
    topic: "Breast cancer evaluation",
    clinicalPattern: "Breast mass / breast disease",
    decisionType: "Next Best Step",
    prompt: "Hard irregular fixed breast mass in a 58-year-old.",
    acceptedAnswers: ["diagnostic mammography", "diagnostic mammogram", "mammography"],
    boardPearl: "Suspicious breast mass in older patients needs diagnostic imaging and biopsy.",
    pivotClue: "Hard irregular fixed mass",
    commonTrap: "reassurance",
    managementPearl: "Start with diagnostic mammography, often with targeted ultrasound.",
    difficulty: 1,
    tags: ["breast cancer", "diagnostic mammography", "fixed mass"]
  },
  {
    system: "Breast",
    topic: "Intraductal papilloma",
    clinicalPattern: "Breast mass / breast disease",
    decisionType: "Diagnosis",
    prompt: "Unilateral spontaneous bloody nipple discharge.",
    acceptedAnswers: ["intraductal papilloma"],
    boardPearl: "Intraductal papilloma causes spontaneous unilateral bloody nipple discharge.",
    pivotClue: "Bloody nipple discharge",
    commonTrap: "galactorrhea",
    managementPearl: "Evaluate pathologic discharge with imaging and tissue diagnosis when indicated.",
    difficulty: 2,
    tags: ["bloody discharge", "intraductal papilloma", "breast"]
  },
  {
    system: "Breast",
    topic: "Paget disease of breast",
    clinicalPattern: "Breast mass / breast disease",
    decisionType: "Diagnosis",
    prompt: "Eczematous nipple changes with underlying breast malignancy.",
    acceptedAnswers: ["paget disease of the breast", "paget disease"],
    boardPearl: "Paget disease causes eczematous nipple changes associated with breast cancer.",
    pivotClue: "Eczematous nipple changes",
    commonTrap: "eczema",
    managementPearl: "Evaluate for underlying breast carcinoma.",
    difficulty: 2,
    tags: ["paget disease", "nipple", "breast cancer"]
  },
  {
    system: "Gynecologic Oncology",
    topic: "Endometrial cancer",
    clinicalPattern: "Gynecologic oncology",
    decisionType: "Diagnosis",
    prompt: "Postmenopausal bleeding.",
    acceptedAnswers: ["endometrial cancer", "endometrial carcinoma"],
    boardPearl: "Postmenopausal bleeding is endometrial cancer until proven otherwise.",
    pivotClue: "Postmenopausal bleeding",
    commonTrap: "atrophic vaginitis only",
    managementPearl: "Evaluate with transvaginal ultrasound or endometrial biopsy.",
    difficulty: 1,
    tags: ["postmenopausal bleeding", "endometrial cancer", "oncology"]
  },
  {
    system: "Gynecologic Oncology",
    topic: "Endometrial cancer risk factor",
    clinicalPattern: "Gynecologic oncology",
    decisionType: "Risk Factor",
    prompt: "Endometrial cancer.",
    acceptedAnswers: ["unopposed estrogen", "obesity", "chronic anovulation"],
    boardPearl: "Unopposed estrogen is the key risk factor for endometrial cancer.",
    pivotClue: "Endometrial proliferation",
    commonTrap: "hpv",
    managementPearl: "Recognize obesity and chronic anovulation as estrogen-excess states.",
    difficulty: 1,
    tags: ["endometrial cancer", "unopposed estrogen", "obesity"]
  },
  {
    system: "Gynecologic Oncology",
    topic: "Cervical cancer",
    clinicalPattern: "Gynecologic oncology",
    decisionType: "Risk Factor",
    prompt: "Cervical cancer.",
    acceptedAnswers: ["hpv 16 and 18", "high-risk hpv", "human papillomavirus"],
    boardPearl: "High-risk HPV, especially 16 and 18, drives cervical cancer.",
    pivotClue: "Cervical squamous dysplasia",
    commonTrap: "unopposed estrogen",
    managementPearl: "Prevention relies on HPV vaccination and screening.",
    difficulty: 1,
    tags: ["cervical cancer", "hpv", "oncology"]
  },
  {
    system: "Gynecologic Oncology",
    topic: "Ovarian cancer",
    clinicalPattern: "Gynecologic oncology",
    decisionType: "Diagnosis",
    prompt: "Older patient with bloating, early satiety, ascites, and adnexal mass.",
    acceptedAnswers: ["ovarian cancer", "epithelial ovarian cancer"],
    boardPearl: "Ovarian cancer often presents late with bloating and ascites.",
    pivotClue: "Ascites with adnexal mass",
    commonTrap: "irritable bowel syndrome",
    managementPearl: "Evaluate suspicious adnexal mass with imaging and tumor markers.",
    difficulty: 1,
    tags: ["ovarian cancer", "ascites", "adnexal mass"]
  },
  {
    system: "Gynecologic Oncology",
    topic: "Krukenberg tumor",
    clinicalPattern: "Gynecologic oncology",
    decisionType: "Most Common Association",
    prompt: "Bilateral mucin-secreting signet-ring ovarian tumors.",
    acceptedAnswers: ["gastric cancer", "stomach cancer", "metastatic gastric cancer"],
    boardPearl: "Krukenberg tumors are ovarian metastases classically from gastric cancer.",
    pivotClue: "Signet-ring ovarian tumor",
    commonTrap: "primary ovarian cancer",
    managementPearl: "Search for a gastrointestinal primary malignancy.",
    difficulty: 2,
    tags: ["krukenberg", "gastric cancer", "ovarian metastasis"]
  },
  {
    system: "Family Planning",
    topic: "Combined oral contraceptives",
    clinicalPattern: "Contraception",
    decisionType: "Contraindication",
    prompt: "Migraine with aura in patient requesting combined oral contraceptives.",
    acceptedAnswers: ["combined oral contraceptives", "estrogen-containing contraception", "combined hormonal contraception"],
    boardPearl: "Estrogen-containing contraception is contraindicated in migraine with aura.",
    pivotClue: "Migraine with aura",
    commonTrap: "progestin-only pill",
    managementPearl: "Choose progestin-only or nonhormonal contraception.",
    difficulty: 1,
    tags: ["contraception", "migraine with aura", "estrogen"]
  },
  {
    system: "Family Planning",
    topic: "Emergency contraception",
    clinicalPattern: "Contraception",
    decisionType: "Management",
    prompt: "Unprotected intercourse 3 days ago; wants most effective emergency contraception.",
    acceptedAnswers: ["copper iud", "copper intrauterine device"],
    boardPearl: "Copper IUD is the most effective emergency contraception.",
    pivotClue: "Most effective emergency contraception",
    commonTrap: "levonorgestrel pill",
    managementPearl: "Copper IUD can be placed within 5 days of unprotected intercourse.",
    difficulty: 1,
    tags: ["emergency contraception", "copper iud", "contraception"]
  },
  {
    system: "Family Planning",
    topic: "Postpartum contraception",
    clinicalPattern: "Contraception",
    decisionType: "Contraindication",
    prompt: "Breastfeeding patient 2 weeks postpartum requesting combined hormonal contraception.",
    acceptedAnswers: ["combined hormonal contraception", "combined oral contraceptives", "estrogen-containing contraception"],
    boardPearl: "Estrogen contraception is avoided early postpartum due to VTE risk and lactation concerns.",
    pivotClue: "2 weeks postpartum",
    commonTrap: "progestin-only contraception",
    managementPearl: "Use progestin-only or nonhormonal options early postpartum.",
    difficulty: 2,
    tags: ["postpartum", "contraception", "estrogen"]
  },
  {
    system: "Family Planning",
    topic: "IUD contraindication",
    clinicalPattern: "Contraception",
    decisionType: "Contraindication",
    prompt: "Active pelvic inflammatory disease and desire for IUD.",
    acceptedAnswers: ["iud placement", "intrauterine device placement"],
    boardPearl: "Active pelvic infection is a contraindication to IUD placement.",
    pivotClue: "Active PID",
    commonTrap: "copper iud",
    managementPearl: "Treat infection first; place IUD after infection resolves.",
    difficulty: 1,
    tags: ["iud", "pid", "contraindication"]
  },
  {
    system: "Family Planning",
    topic: "Depot medroxyprogesterone",
    clinicalPattern: "Contraception",
    decisionType: "Complication",
    prompt: "Long-term depot medroxyprogesterone acetate use.",
    acceptedAnswers: ["bone mineral density loss", "decreased bone mineral density", "weight gain"],
    boardPearl: "Depot medroxyprogesterone can reduce bone mineral density with long-term use.",
    pivotClue: "Long-term DMPA use",
    commonTrap: "endometrial cancer",
    managementPearl: "Counsel on reversible bone density loss and alternative options when appropriate.",
    difficulty: 2,
    tags: ["dmpa", "contraception", "bone density"]
  },
  {
    system: "Menopause and Urogynecology",
    topic: "Genitourinary syndrome of menopause",
    clinicalPattern: "Menopause / urinary symptoms",
    decisionType: "Diagnosis",
    prompt: "Postmenopausal vaginal dryness, dyspareunia, and recurrent irritation.",
    acceptedAnswers: ["genitourinary syndrome of menopause", "vaginal atrophy", "atrophic vaginitis"],
    boardPearl: "Hypoestrogenism causes vaginal atrophy and urinary symptoms after menopause.",
    pivotClue: "Postmenopausal vaginal dryness",
    commonTrap: "vulvovaginal candidiasis",
    managementPearl: "Use vaginal estrogen for persistent symptoms without contraindications.",
    difficulty: 1,
    tags: ["menopause", "vaginal atrophy", "dyspareunia"]
  },
  {
    system: "Menopause and Urogynecology",
    topic: "Menopausal vasomotor symptoms",
    clinicalPattern: "Menopause / urinary symptoms",
    decisionType: "Management",
    prompt: "Healthy recently menopausal patient with severe hot flashes.",
    acceptedAnswers: ["menopausal hormone therapy", "hormone therapy", "estrogen therapy"],
    boardPearl: "Hormone therapy is most effective for vasomotor symptoms in appropriate candidates.",
    pivotClue: "Severe hot flashes in healthy recently menopausal patient",
    commonTrap: "vaginal estrogen only",
    managementPearl: "Use combined estrogen-progestin if uterus is present.",
    difficulty: 1,
    tags: ["menopause", "hot flashes", "hormone therapy"]
  },
  {
    system: "Menopause and Urogynecology",
    topic: "Stress urinary incontinence",
    clinicalPattern: "Menopause / urinary symptoms",
    decisionType: "Diagnosis",
    prompt: "Urine leakage with coughing, laughing, and exercise.",
    acceptedAnswers: ["stress urinary incontinence", "stress incontinence"],
    boardPearl: "Leakage with increased intra-abdominal pressure is stress incontinence.",
    pivotClue: "Leakage with coughing or exercise",
    commonTrap: "urge incontinence",
    managementPearl: "Start with pelvic floor muscle exercises.",
    difficulty: 1,
    tags: ["urinary incontinence", "stress", "kegel"]
  },
  {
    system: "Menopause and Urogynecology",
    topic: "Urge urinary incontinence",
    clinicalPattern: "Menopause / urinary symptoms",
    decisionType: "Diagnosis",
    prompt: "Sudden intense urge to void followed by urine leakage.",
    acceptedAnswers: ["urge urinary incontinence", "overactive bladder", "urge incontinence"],
    boardPearl: "Urgency followed by leakage is urge incontinence.",
    pivotClue: "Sudden urge before leakage",
    commonTrap: "stress urinary incontinence",
    managementPearl: "Start bladder training and behavioral therapy.",
    difficulty: 1,
    tags: ["urinary incontinence", "urge", "overactive bladder"]
  },
  {
    system: "Menopause and Urogynecology",
    topic: "Pelvic organ prolapse",
    clinicalPattern: "Menopause / urinary symptoms",
    decisionType: "Management",
    prompt: "Symptomatic pelvic organ prolapse in patient desiring nonsurgical therapy.",
    acceptedAnswers: ["pessary", "vaginal pessary"],
    boardPearl: "Pessary is a nonsurgical option for symptomatic pelvic organ prolapse.",
    pivotClue: "Desires nonsurgical therapy",
    commonTrap: "hysterectomy",
    managementPearl: "Offer pessary and pelvic floor therapy when appropriate.",
    difficulty: 1,
    tags: ["pelvic organ prolapse", "pessary", "urogynecology"]
  }
];

async function main() {
  for (const decision of decisions) {
    const existingDecision = await prisma.clinicalDecision.findFirst({
      where: {
        specialty: "OB/GYN",
        system: decision.system,
        topic: decision.topic
      },
      select: { id: true }
    });
    const data = {
      specialty: "OB/GYN",
      system: decision.system,
      topic: decision.topic,
      clinicalPattern: decision.clinicalPattern,
      decisionType: decision.decisionType,
      prompt: decision.prompt,
      acceptedAnswers: JSON.stringify(decision.acceptedAnswers),
      boardPearl: decision.boardPearl,
      pivotClue: decision.pivotClue,
      commonTrap: decision.commonTrap,
      managementPearl: decision.managementPearl,
      relatedDecisionIds: JSON.stringify([]),
      difficulty: decision.difficulty,
      tags: JSON.stringify(decision.tags)
    };

    if (existingDecision) {
      await prisma.clinicalDecision.update({
        where: { id: existingDecision.id },
        data
      });
    } else {
      await prisma.clinicalDecision.create({
        data
      });
    }
  }

  console.log(`Seeded ${decisions.length} OB/GYN clinical decisions.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
